install.packages("sas7bdat")
library(sas7bdat)
setwd("~/Master of Science in Analytics/Logistic Regression/Homework 1")
read.sas7bdat("insurance_t.sas7bdat")
homeworkonelog<-read.sas7bdat("insurance_t.sas7bdat")
logit.model<-glm(INS~ACCTAGE, data=homeworkonelog, family = binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~DDABAL, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~DEP, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~DEPAMT, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~CASHBK, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~CHECKS, data=homeworkonelog, family=binomial(link="logit"))
summary(logit.model)
logit.model<-glm(INS~NSFAMT, data=homeworkonelog, family=binomial(link="logit"))
summary(logit.model)
logit.model<-glm(INS~PHONE, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~TELLER, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~SAVBAL, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~ATMAMT, data=homeworkonelog, family=binomial(link="logit"))
summary(logit.model)
logit.model<-glm(INS~POS, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~POSAMT, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~CDBAL, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~IRABAL, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~LOCBAL, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~INVBAL, data=homeworkonelog, family=binomail(link="logit"))
summary(logit.model)
logit.model<-glm(INS~ILSBAL, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~MMBAL, data = homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~MMCRED, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~MTGBAL, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~CCBAL, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~CCPURC, data = homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~INCOME, data = homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~LORES, data=homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~HMVAL, data = homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~AGE, data = homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
logit.model<-glm(INS~CRSCORE, data = homeworkonelog, family=binomial(link = "logit"))
summary(logit.model)
install.packages("mgcv")
library(mgcv)
fit.gam<-gam(INS~s(ACCTAGE), data=homeworkonelog, family=binomial(link = "logit"),method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(DDABAL), data=homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(DEP), data=homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(DEPAMT), data=homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(CASHBK), data=homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(CHECKS), data=homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(NSFAMT), data=homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(PHONE), data=homeworkonelog, family=binomial(link="logit"), method = "REML")
summary(fit.gam)
fit.gam<-gam(INS~s(TELLER), data=homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(SAVBAL), data=homeworkonelog, family=binomial(link = "logit"), method = "REML")
summary(fit.gam)
fit.gam<-gam(INS~s(ATMAMT), data=homeworkonelog, family=binomial(link = "logit"), method= "REML")
summary(fit.gam)
fit.gam<-gam(INS~s(POS), data=homeworkonelog, family=binomial(link="logit"), methdo="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(POSAMT), data = homeworkonelog, family=binomial(link="logit"), method = "REML")
summary(fit.gam)
fit.gam<-gam(INS~s(CDBAL), data = homeworkonelog, family=binomial(link = ="logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(IRABAL), data = homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(LOCBAL), data = homeworkonelog, family=binomial(link = "REML"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(INVBAL), data=homeworkonelog, family=binomial(link = "logit"), method = "REML")
summary(fit.gam)
fit.gam<-gam(INS~s(ILSBAL), data = homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(MMBAL), data=homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(MMCRED), data = homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(MTGBAL), data = homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(CCBAL), data = homeworkonelog, family=binomial(link = "logit"), method = "REML")
summary(fit.gam)
#fit.gam<-gam(INS~s(CCPURC), data = homeworkonelog, family=binomial(link = "logit"), method = "REML")
#summary(fit.gam)
fit.gam<-gam(INS~s(INCOME), data = homeworkonelog, family=binomial(link = "logit"), method = "REML")
summary(fit.gam)
fit.gam<-gam(INS~s(LORES), data = homeworkonelog, family=binomial(link = "logit"), method = "REML")
summary(fit.gam)
fit.gam<-gam(INS~s(HMVAL), data = homeworkonelog, family=binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(AGE), data = homeworkonelog, family = binomial(link = "logit"), method="REML")
summary(fit.gam)
fit.gam<-gam(INS~s(CRSCORE), data = homeworkonelog, family=binomial(link = "logit"), method = "REML")
summary(fit.gam)
hist(homeworkonelog$ACCTAGE)
hist(homeworkonelog$DDABAL)
hist(homeworkonelog$DEP)
hist(homeworkonelog$DEPAMT)
hist(homeworkonelog$CASHBK)
hist(homeworkonelog$CHECKS)
hist(homeworkonelog$NSFAMT)
hist(homeworkonelog$PHONE)
hist(homeworkonelog$TELLER)
hist(homeworkonelog$SAVBAL)
hist(homeworkonelog$ATMAMT)
hist(homeworkonelog$POS)
hist(homeworkonelog$POSAMT)
hist(homeworkonelog$CDBAL)
hist(homeworkonelog$IRABAL)
hist(homeworkonelog$LOCBAL)
hist(homeworkonelog$INVBAL)
hist(homeworkonelog$ILSBAL)
hist(homeworkonelog$MMBAL)
hist(homeworkonelog$MMCRED)
hist(homeworkonelog$MTGBAL)
hist(homeworkonelog$CCBAL)
hist(homeworkonelog$CCPURC)
hist(homeworkonelog$INCOME)
hist(homeworkonelog$LORES)
hist(homeworkonelog$HMVAL)
hist(homeworkonelog$AGE)
hist(homeworkonelog$CRSCORE)